"""Degradation detection — compares current run against baseline to raise alerts.

Alert levels:
  - INFO: Normal operation.
  - WARNING: Minor deviation (confidence < 1σ below mean, or single run failure).
  - CRITICAL: Significant deviation (confidence < 2σ below mean, or pass rate drop).
"""

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from guardrails.engine import GuardrailResult
from monitoring.baseline import RollingBaseline
from monitoring.store import DriftStore

logger = logging.getLogger(__name__)


class AlertLevel(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


@dataclass
class DegradationAlert:
    """A degradation alert generated by comparing current run to baseline."""

    level: AlertLevel
    message: str
    agent_name: str = "default"
    current_confidence: float = 0.0
    baseline_mean: float = 0.0
    baseline_std: float = 0.0
    pass_rate_current: float = 0.0
    pass_rate_baseline: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return f"[{self.level.value}] {self.agent_name}: {self.message}"


class DegradationDetector:
    """Detects quality degradation by comparing current results to the baseline.

    Usage:
        detector = DegradationDetector(store=store, baseline=baseline)
        alert = detector.check(result, agent_name="my_agent")
        if alert.level != AlertLevel.INFO:
            logger.warning("DEGRADATION: %s", alert)
    """

    def __init__(
        self,
        store: DriftStore,
        baseline: RollingBaseline,
        confidence_threshold_warn: float = 1.0,
        confidence_threshold_crit: float = 2.0,
        pass_rate_threshold: float = 0.7,
    ) -> None:
        """Initialize the degradation detector.

        Args:
            store: DriftStore for persistent storage.
            baseline: RollingBaseline for computing statistics.
            confidence_threshold_warn: Number of standard deviations below mean
                                       to trigger WARNING.
            confidence_threshold_crit: Number of standard deviations below mean
                                       to trigger CRITICAL.
            pass_rate_threshold: Minimum pass rate fraction to avoid CRITICAL alert.
        """
        self._store = store
        self._baseline = baseline
        self._confidence_threshold_warn = confidence_threshold_warn
        self._confidence_threshold_crit = confidence_threshold_crit
        self._pass_rate_threshold = pass_rate_threshold

    def check(
        self,
        result: GuardrailResult,
        agent_name: str = "default",
    ) -> DegradationAlert:
        """Check a current result against the baseline for degradation.

        Args:
            result: The current GuardrailResult to evaluate.
            agent_name: Agent identifier for querying the right baseline.

        Returns:
            A DegradationAlert indicating the severity level.
        """
        stats = self._baseline.compute(agent_name=agent_name)

        current_conf = result.aggregate_confidence
        current_pass = 1.0 if result.overall_pass else 0.0

        # If no baseline data yet, just report INFO
        if stats["window_size"] == 0:
            return DegradationAlert(
                level=AlertLevel.INFO,
                message="Insufficient baseline data for degradation detection.",
                agent_name=agent_name,
                current_confidence=current_conf,
            )

        conf_mean = stats["confidence_mean"]
        conf_std = stats["confidence_std"]

        # Compute how many std deviations below mean
        if conf_std > 0:
            deviation = (conf_mean - current_conf) / conf_std
        else:
            deviation = 0.0

        pass_rate_window = stats["pass_rate_values"] + [current_pass]
        pass_rate = sum(pass_rate_window) / len(pass_rate_window)

        details = {
            "current_confidence": current_conf,
            "baseline_confidence_mean": conf_mean,
            "baseline_confidence_std": conf_std,
            "deviation_sigma": deviation,
            "current_pass_rate": pass_rate,
            "baseline_pass_rate": stats["pass_rate_mean"],
            "window_size": stats["window_size"],
        }

        # CRITICAL: confidence > 2σ below or pass rate drops below threshold
        if deviation > self._confidence_threshold_crit:
            return DegradationAlert(
                level=AlertLevel.CRITICAL,
                message=(
                    f"Aggregate confidence {current_conf:.2f} is {deviation:.1f}σ "
                    f"below baseline mean {conf_mean:.2f}. "
                    f"Pass rate: {pass_rate:.2f}."
                ),
                agent_name=agent_name,
                current_confidence=current_conf,
                baseline_mean=conf_mean,
                baseline_std=conf_std,
                pass_rate_current=pass_rate,
                pass_rate_baseline=stats["pass_rate_mean"],
                details=details,
            )

        if pass_rate < self._pass_rate_threshold:
            return DegradationAlert(
                level=AlertLevel.CRITICAL,
                message=(
                    f"Pass rate {pass_rate:.2f} dropped below threshold "
                    f"{self._pass_rate_threshold}. Baseline: {stats['pass_rate_mean']:.2f}."
                ),
                agent_name=agent_name,
                current_confidence=current_conf,
                baseline_mean=conf_mean,
                baseline_std=conf_std,
                pass_rate_current=pass_rate,
                pass_rate_baseline=stats["pass_rate_mean"],
                details=details,
            )

        # WARNING: confidence > 1σ below
        if deviation > self._confidence_threshold_warn:
            return DegradationAlert(
                level=AlertLevel.WARNING,
                message=(
                    f"Aggregate confidence {current_conf:.2f} is {deviation:.1f}σ "
                    f"below baseline mean {conf_mean:.2f}."
                ),
                agent_name=agent_name,
                current_confidence=current_conf,
                baseline_mean=conf_mean,
                baseline_std=conf_std,
                pass_rate_current=pass_rate,
                pass_rate_baseline=stats["pass_rate_mean"],
                details=details,
            )

        # INFO: everything looks normal
        return DegradationAlert(
            level=AlertLevel.INFO,
            message=f"Normal operation. Confidence: {current_conf:.2f}, Pass rate: {pass_rate:.2f}.",
            agent_name=agent_name,
            current_confidence=current_conf,
            baseline_mean=conf_mean,
            baseline_std=conf_std,
            pass_rate_current=pass_rate,
            pass_rate_baseline=stats["pass_rate_mean"],
            details=details,
        )
